### ISSUE TITLE
Unity doesn't start with gtk3-nocsd

### ISSUE THREAD

**Issue by hotice** [PCMan/gtk3-nocsd#1]
Ubuntu 14.04: Unity doesn't start when adding "export LD_PRELOAD=/path/to/gtk3-nocsd.so" to ~/.profile Maybe because you make GTK think that there is no compositor available and this causes Unity to fail? Maybe you can somehow whitelist Unity so gtk3-nocsd doesn't break it?

I tested it on my laptop (64bit) as well as a fresh virtual machine (32bit), both running Ubuntu 14.04 and GTK 3.10.8.

**Comment by chris-se** [comment]
Does this still occur with version 1 of gtk3-nocsd? There have been a couple of crashes related to plugins and/or Gtk2 that were fixed, so maybe Unity not starting was a crash.

**Comment by hotice** [comment]
I just tried it in Ubuntu 14.04 and Unity did start, so this looks fixed with the latest version. Thanks!
