### ISSUE TITLE
Not working on sc-controller

### ISSUE THREAD

**Issue by Xylemon** [PCMan/gtk3-nocsd#16]
This project (https://github.com/kozec/sc-controller) which provides a GTK3+ GUI with a CSD titlebar remains to have no window border with gtk3-nocsd. I can confirm that my install is working correctly, as gtk3-nocsd works on other GTK3+ CSD apps flawlessly. You can use the GUI without a Steam Controller, so testing out sc-controller shouldn't be a problem. I am also on Arch Linux 64-bit with XFCE4 (xfwm4 is the window manager) using latest git for gtk3-nocsd if that matters.

**Comment by chris-se** [comment]
I can confirm that this is the case (on Debian Stretch, with the latest gtk3-nocsd v3), and a first cursory examination indicates that the GtkWindow/GtkDialog `class_init` overrides don't seem to be called, even though the type register override (that sets them) is. This is very strange, I'll have to look into that.

**Comment by chris-se** [comment]
Hmm, interesting, on Debian Jessie (older Gtk+3 version, 3.14) the problem doesn't occur. So there was apparently a change in Gtk somewhere between 3.14 (Jessie) and 3.20 (Stretch) that caused this to fail. Hopefully that'll make it easier to debug this.

**Comment by chris-se** [comment]
I found the problem and fixed it in git master, it would be great if you could verify that.

**Comment by Xylemon** [comment]
Tested latest git and it worked! Thanks for investigating.
