### ISSUE TITLE
deadbeef crashes in the gtk2 plugin

### ISSUE THREAD

**Issue by stqn1** [PCMan/gtk3-nocsd#2]
I just compiled and installed gtk3-nocsd as recommended in the README (except I put the exports in ~/.zprofile since I use zsh), on Arch Linux 64 bit, and rebooted. Most programs seem to work fine (and CoreBird now has window borders!), but deadbeef crashes:

starting deadbeef 0.6.2
(...)
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /usr/lib/deadbeef/ddb_gui_GTK2.so
(...)
convgui: gtkui plugin not found
plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK3 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK3 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 2.24.24
Segmentation Fault
backtrace() returned 2 addresses
deadbeef() [0x403aa1]
/usr/lib/libc.so.6(+0x33df0) [0x7f7cf237bdf0]

gdb backtrace:
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7bdb14a in g_type_register_static_simple ()
   from /mnt/disk/builds/gtk3-nocsd/gtk3-nocsd/gtk3-nocsd.so
#2  0x00007ffff655271c in gdk_display_manager_get_type ()
   from /usr/lib/libgdk-x11-2.0.so.0
#3  0x00007ffff6552759 in gdk_display_manager_get ()
   from /usr/lib/libgdk-x11-2.0.so.0
#4  0x00007ffff692e30b in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#5  0x00007ffff6914cc8 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#6  0x00007ffff47eebb7 in g_option_context_parse ()
   from /usr/lib/libglib-2.0.so.0
#7  0x00007ffff6915238 in gtk_parse_args () from /usr/lib/libgtk-x11-2.0.so.0
#8  0x00007ffff6915299 in gtk_init_check () from /usr/lib/libgtk-x11-2.0.so.0
#9  0x00007ffff69152b9 in gtk_init () from /usr/lib/libgtk-x11-2.0.so.0
#10 0x00007ffff6e90c04 in gtkui_thread ()
   from /usr/lib/deadbeef/ddb_gui_GTK2.so
#11 0x00007ffff6e914d9 in ?? () from /usr/lib/deadbeef/ddb_gui_GTK2.so
#12 0x00000000004036b8 in ?? ()
#13 0x00007ffff7126000 in __libc_start_main () from /usr/lib/libc.so.6
#14 0x000000000040398a in ?? ()

**Comment by chris-se** [comment]
This is now fixed, please try version 1.
