### ISSUE TITLE
Gnome-maps still shows CSD

### ISSUE THREAD

**Issue by natanvarga** [PCMan/gtk3-nocsd#29]
It works great with most apps except for gnome-maps which still shows CSD and not the DE specific window decoration.
My setup: Manjaro Linux (Arch based), cinnamon DE, gtk3-nocsd-git installed.

**Comment by ghost** [comment]
works here

![screenshot from 2017-12-30 14-39-13](https://user-images.githubusercontent.com/3780774/34457188-3e135aae-ed6f-11e7-9208-bf62ab3398d7.png)

**Comment by natanvarga** [comment]
Looking good on my end now as well. Don't know what caused the malfunction.
