### ISSUE TITLE
Nautilus (3.26.x) crashes (segfault) on Ubuntu 18.04

### ISSUE THREAD

**Issue by khurshid-alam** [PCMan/gtk3-nocsd#32]
When I try to enable it for nautilus it crashes. I will try to get a gdb trace.

**Comment by khurshid-alam** [comment]
@PCMan Can you reproduce?

**Comment by khurshid-alam** [comment]
I can reproduce with 18.04 as well with 3.26.x

**Comment by jbicha** [comment]
@khurshid-alam Nautilus runs fine without crashing here. Can you duplicate with a clean profile or from a new install?

I installed unity and gtk3-nocsd on Ubuntu 18.04 Alpha. After rebooting, I logged into Unity and ran nautilus.

**Comment by khurshid-alam** [comment]
@jbicha 

Yes. I tried with clean install (our ubuntu-unity-amd64.iso) and I can't reproduce. Closing. Thanks.

**Comment by skyide** [comment]
The problem is real, here is a prove and it happens intermittently, I can't reproduce it at will:

```
ERROR:../src/nautilus-file.c:587:nautilus_file_new_from_filename: assertion failed: (filename[0] != '\0')

Thread 1 "nautilus" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

```
