### ISSUE TITLE
Pulseaudio doesn't start with gtk3-nocsd

### ISSUE THREAD

**Issue by avDuma** [PCMan/gtk3-nocsd#4]
Here's the error I get when I try to launch pulseaudio with gtk3-nocsd added to my .bashrc file.

[albi@albi-desktop ~]$ pulseaudio --start
pulseaudio: symbol lookup error: /home/albi/.config/gtk3-nocsd.so: undefined symbol: gtk_window_get_type

**Comment by rainerborene** [comment]
Same here.

**Comment by chris-se** [comment]
This is now fixed, please try version 1.
