### ISSUE TITLE
gtk3-nocsd breaks the save/open dialog

### ISSUE THREAD

**Issue by afraidofmusic** [PCMan/gtk3-nocsd#57]
On Arch Linux, in Sway, using the [gtk3-nocsd-git](https://aur.archlinux.org/packages/gtk3-nocsd-git/) package.
Added the following lines to `.zprofile`

`export GTK_CSD=0`
`export LD_PRELOAD=/usr/lib/libgtk3-nocsd.so.0`

This leaves the open/save dialogs unusable. There is no button to open/save, and cannot use keyboard to open/save.

Without gtk3-nocsd
![2020-08-26T10:21:17,867744990+03:00](https://user-images.githubusercontent.com/25895258/91274336-0edced80-e76e-11ea-997f-898af158bc15.png)

With gtk3-nocsd
![2020-08-26T10:22:24,056822156+03:00](https://user-images.githubusercontent.com/25895258/91274342-10a6b100-e76e-11ea-8b9a-f78634b3d223.png)

**Comment by neoninteger** [comment]
Hi, I'm the maintainer of the `gtk3-nocsd-git` AUR package. The package actually pulls from a fork of this repository located here: https://github.com/ZaWertun/gtk3-nocsd

And this issue has already been reported there as https://github.com/ZaWertun/gtk3-nocsd/issues/5

**Comment by afraidofmusic** [comment]
Sorry, I didn't realize that. Installed from this repository and all's good.
